# Generated by Django 5.1.3 on 2024-12-04 02:49

import apppo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[apppo.models.validate_csv]),
        ),
    ]
